services:
  php:
    name: dev_php
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./php/config/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./src:/var/www/html
  web:
    name: dev_web
    image: docker.io/library/nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
